//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cats.Services.Common {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class ApplicationSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ApplicationSettings defaultInstance = ((ApplicationSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ApplicationSettings())));
        
        public static ApplicationSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PSNPWorkflow")]
        public string PSNPWorkflow {
            get {
                return ((string)(this["PSNPWorkflow"]));
            }
            set {
                this["PSNPWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PaymentRequestWorkflow")]
        public string PaymentRequestWorkflow {
            get {
                return ((string)(this["PaymentRequestWorkflow"]));
            }
            set {
                this["PaymentRequestWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TransporterChequeWorkflow")]
        public string TransporterChequeWorkflow {
            get {
                return ((string)(this["TransporterChequeWorkflow"]));
            }
            set {
                this["TransporterChequeWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TransporterPaymentRequestWorkflow")]
        public string TransporterPaymentRequestWorkflow {
            get {
                return ((string)(this["TransporterPaymentRequestWorkflow"]));
            }
            set {
                this["TransporterPaymentRequestWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultRation")]
        public string DefaultRation {
            get {
                return ((string)(this["DefaultRation"]));
            }
            set {
                this["DefaultRation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HRDWorkflow")]
        public string HRDWorkflow {
            get {
                return ((string)(this["HRDWorkflow"]));
            }
            set {
                this["HRDWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReliefRequisitionWorkflow")]
        public string ReliefRequisitionWorkflow {
            get {
                return ((string)(this["ReliefRequisitionWorkflow"]));
            }
            set {
                this["ReliefRequisitionWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LocalPurchaseReceiptPlanWorkflow")]
        public string LocalPurchaseReceiptPlanWorkflow {
            get {
                return ((string)(this["LocalPurchaseReceiptPlanWorkflow"]));
            }
            set {
                this["LocalPurchaseReceiptPlanWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SwapWorkflow")]
        public string SwapWorkflow {
            get {
                return ((string)(this["SwapWorkflow"]));
            }
            set {
                this["SwapWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RegionalRequestWorkflow")]
        public string RegionalRequestWorkflow {
            get {
                return ((string)(this["RegionalRequestWorkflow"]));
            }
            set {
                this["RegionalRequestWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TransportOrderWorkflow")]
        public string TransportOrderWorkflow {
            get {
                return ((string)(this["TransportOrderWorkflow"]));
            }
            set {
                this["TransportOrderWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReciptPlanForLoanWorkflow")]
        public string ReciptPlanForLoanWorkflow {
            get {
                return ((string)(this["ReciptPlanForLoanWorkflow"]));
            }
            set {
                this["ReciptPlanForLoanWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BidPlanWorkflow")]
        public string BidPlanWorkflow {
            get {
                return ((string)(this["BidPlanWorkflow"]));
            }
            set {
                this["BidPlanWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BidWinnerWorkflow")]
        public string BidWinnerWorkflow {
            get {
                return ((string)(this["BidWinnerWorkflow"]));
            }
            set {
                this["BidWinnerWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NeedAssessmentPlanWorkflow")]
        public string NeedAssessmentPlanWorkflow {
            get {
                return ((string)(this["NeedAssessmentPlanWorkflow"]));
            }
            set {
                this["NeedAssessmentPlanWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NeedAssessmentWorkflow")]
        public string NeedAssessmentWorkflow {
            get {
                return ((string)(this["NeedAssessmentWorkflow"]));
            }
            set {
                this["NeedAssessmentWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TransportRequisitionWorkflow")]
        public string TransportRequisitionWorkflow {
            get {
                return ((string)(this["TransportRequisitionWorkflow"]));
            }
            set {
                this["TransportRequisitionWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DonationPlanHeaderWorkflow")]
        public string DonationPlanHeaderWorkflow {
            get {
                return ((string)(this["DonationPlanHeaderWorkflow"]));
            }
            set {
                this["DonationPlanHeaderWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GiftCertificateWorkflow")]
        public string GiftCertificateWorkflow {
            get {
                return ((string)(this["GiftCertificateWorkflow"]));
            }
            set {
                this["GiftCertificateWorkflow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TranferReceiptPlanWorkflow")]
        public string TranferReceiptPlanWorkflow {
            get {
                return ((string)(this["TranferReceiptPlanWorkflow"]));
            }
            set {
                this["TranferReceiptPlanWorkflow"] = value;
            }
        }
    }
}
