IF  NOT EXISTS (
  SELECT * 
  FROM   sys.columns 
  WHERE  object_id = OBJECT_ID(N'[dbo].[TableName]') 
         AND name = 'BusinessProcessID'
)
 

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE Schema_.TableName ADD
	BusinessProcessID int NULL
GO
ALTER TABLE Schema_.TableName ADD 
BusinessProcessID int NOT NULL CONSTRAINT DF_TableName_BusinessProcessID DEFAULT 0

GO
ALTER TABLE Schema_.TableName SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

