
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Adjustment
	DROP CONSTRAINT DF__Adjustment__Busine__639B30FA
GO
ALTER TABLE dbo.Adjustment
	DROP COLUMN BusinessProcessID
GO
ALTER TABLE dbo.Adjustment SET (LOCK_ESCALATION = TABLE)
GO
COMMIT